export const conditionTranslations = [
    { condition: 'clearsky_day', translation: 'klar himmel', icon: '01d.png' },
    { condition: 'clearsky_night', translation: 'klar himmel', icon: '01n.png' },
    { condition: 'clearsky_polartwilight', translation: 'klar himmel', icon: '01m.png' },
    { condition: 'fair_day', translation: 'fint väder', icon: '02d.png' },
    { condition: 'fair_night', translation: 'fint väder', icon: '02n.png' },
    { condition: 'fair_polartwilight', translation: 'fint väder', icon: '02m.png' },
    { condition: 'partlycloudy_day', translation: 'delvis molnigt', icon: '03d.png' },
    { condition: 'partlycloudy_night', translation: 'delvis molnigt', icon: '03n.png' },
    { condition: 'partlycloudy_polartwilight', translation: 'delvis molnigt', icon: '03m.png' },
    { condition: 'cloudy', translation: 'molnigt', icon: '04.png' },
    { condition: 'rainshowers_day', translation: 'regnskurar', icon: '05d.png' },
    { condition: 'rainshowers_night', translation: 'regnskurar', icon: '05n.png' },
    { condition: 'rainshowers_polartwilight', translation: 'regnskurar', icon: '05m.png' },
    { condition: 'rainshowersandthunder_day', translation: 'regnskurar och åska', icon: '06d.png' },
    { condition: 'rainshowersandthunder_night', translation: 'regnskurar och åska', icon: '06n.png' },
    { condition: 'rainshowersandthunder_polartwilight', translation: 'regnskurar och åska', icon: '06m.png' },
    { condition: 'sleetshowers_day', translation: 'blandat regn och snö', icon: '07d.png' },
    { condition: 'sleetshowers_night', translation: 'blandat regn och snö', icon: '07n.png' },
    { condition: 'sleetshowers_polartwilight', translation: 'blandat regn och snö', icon: '07m.png' },
    { condition: 'snowshowers_day', translation: 'snöbyar', icon: '08d.png' },
    { condition: 'snowshowers_night', translation: 'snöbyar', icon: '08n.png' },
    { condition: 'snowshowers_polartwilight', translation: 'snöbyar', icon: '08m.png' },
    { condition: 'rain', translation: 'regn', icon: '09.png' },
    { condition: 'heavyrain', translation: 'kraftigt regn', icon: '10.png' },
    { condition: 'heavyrainandthunder', translation: 'kraftigt regn och åska', icon: '11.png' },
    { condition: 'sleet', translation: 'blandat regn och snö', icon: '12.png' },
    { condition: 'snow', translation: 'snö', icon: '13.png' },
    { condition: 'snowandthunder', translation: 'snö och åska', icon: '14.png' },
    { condition: 'fog', translation: 'dimma', icon: '15.png' },
    { condition: 'sleetshowersandthunder_day', translation: 'blandat regn och snö med åska', icon: '20d.png' },
    { condition: 'sleetshowersandthunder_night', translation: 'blandat regn och snö med åska', icon: '20n.png' },
    { condition: 'sleetshowersandthunder_polartwilight', translation: 'blandat regn och snö med åska', icon: '20m.png' },
    { condition: 'snowshowersandthunder_day', translation: 'snöbyar och åska', icon: '21d.png' },
    { condition: 'snowshowersandthunder_night', translation: 'snöbyar och åska', icon: '21n.png' },
    { condition: 'snowshowersandthunder_polartwilight', translation: 'snöbyar och åska', icon: '21m.png' },
    { condition: 'rainandthunder', translation: 'regn och åska', icon: '22.png' },
    { condition: 'sleetandthunder', translation: 'blandat regn och snö med åska', icon: '23.png' },
    { condition: 'lightrainshowersandthunder_day', translation: 'lätta regnskurar och åska', icon: '24d.png' },
    { condition: 'lightrainshowersandthunder_night', translation: 'lätta regnskurar och åska', icon: '24n.png' },
    { condition: 'lightrainshowersandthunder_polartwilight', translation: 'lätta regnskurar och åska', icon: '24m.png' },
    { condition: 'heavyrainshowersandthunder_day', translation: 'kraftiga regnskurar och åska', icon: '25d.png' },
    { condition: 'heavyrainshowersandthunder_night', translation: 'kraftiga regnskurar och åska', icon: '25n.png' },
    { condition: 'heavyrainshowersandthunder_polartwilight', translation: 'kraftiga regnskurar och åska', icon: '25m.png' },
    { condition: 'lightssleetshowersandthunder_day', translation: 'lätta blandade regn och snöskurar med åska', icon: '26d.png' },
    { condition: 'lightssleetshowersandthunder_night', translation: 'lätta blandade regn och snöskurar med åska', icon: '26n.png' },
    { condition: 'lightssleetshowersandthunder_polartwilight', translation: 'lätta blandade regn och snöskurar med åska', icon: '26m.png' },
    { condition: 'heavysleetshowersandthunder_day', translation: 'kraftiga blandade regn och snöskurar med åska', icon: '27d.png' },
    { condition: 'heavysleetshowersandthunder_night', translation: 'kraftiga blandade regn och snöskurar med åska', icon: '27n.png' },
    { condition: 'heavysleetshowersandthunder_polartwilight', translation: 'kraftiga blandade regn och snöskurar med åska', icon: '27m.png' },
    { condition: 'lightssnowshowersandthunder_day', translation: 'lätta snöskurar med åska', icon: '28d.png' },
    { condition: 'lightssnowshowersandthunder_night', translation: 'lätta snöskurar med åska', icon: '28n.png' },
    { condition: 'lightssnowshowersandthunder_polartwilight', translation: 'lätta snöskurar med åska', icon: '28m.png' },
    { condition: 'heavysnowshowersandthunder_day', translation: 'kraftiga snöskurar med åska', icon: '29d.png' },
    { condition: 'heavysnowshowersandthunder_night', translation: 'kraftiga snöskurar med åska', icon: '29n.png' },
    { condition: 'heavysnowshowersandthunder_polartwilight', translation: 'kraftiga snöskurar med åska', icon: '29m.png' },
    { condition: 'lightrainandthunder', translation: 'lätt regn och åska', icon: '30.png' },
    { condition: 'lightsleetandthunder', translation: 'lätt blandat regn och snö med åska', icon: '31.png' },
    { condition: 'heavysleetandthunder', translation: 'kraftigt blandat regn och snö med åska', icon: '32.png' },
    { condition: 'lightsnowandthunder', translation: 'lätt snö och åska', icon: '33.png' },
    { condition: 'heavysnowandthunder', translation: 'kraftigt snö och åska', icon: '34.png' },
    { condition: 'lightrainshowers_day', translation: 'lätta regnskurar', icon: '40d.png' },
    { condition: 'lightrainshowers_night', translation: 'lätta regnskurar', icon: '40n.png' },
    { condition: 'lightrainshowers_polartwilight', translation: 'lätta regnskurar', icon: '40m.png' },
    { condition: 'heavyrainshowers_day', translation: 'kraftiga regnskurar', icon: '41d.png' },
    { condition: 'heavyrainshowers_night', translation: 'kraftiga regnskurar', icon: '41n.png' },
    { condition: 'heavyrainshowers_polartwilight', translation: 'kraftiga regnskurar', icon: '41m.png' },
    { condition: 'lightsleetshowers_day', translation: 'lätta blandade regn och snöskurar', icon: '42d.png' },
    { condition: 'lightsleetshowers_night', translation: 'lätta blandade regn och snöskurar', icon: '42n.png' },
    { condition: 'lightsleetshowers_polartwilight', translation: 'lätta blandade regn och snöskurar', icon: '42m.png' },
    { condition: 'heavysleetshowers_day', translation: 'kraftiga blandade regn och snöskurar', icon: '43d.png' },
    { condition: 'heavysleetshowers_night', translation: 'kraftiga blandade regn och snöskurar', icon: '43n.png' },
    { condition: 'heavysleetshowers_polartwilight', translation: 'kraftiga blandade regn och snöskurar', icon: '43m.png' },
    { condition: 'lightsnowshowers_day', translation: 'lätta snöskurar', icon: '44d.png' },
    { condition: 'lightsnowshowers_night', translation: 'lätta snöskurar', icon: '44n.png' },
    { condition: 'lightsnowshowers_polartwilight', translation: 'lätta snöskurar', icon: '44m.png' },
    { condition: 'heavysnowshowers_day', translation: 'kraftiga snöskurar', icon: '45d.png' },
    { condition: 'heavysnowshowers_night', translation: 'kraftiga snöskurar', icon: '45n.png' },
    { condition: 'heavysnowshowers_polartwilight', translation: 'kraftiga snöskurar', icon: '45m.png' },
    { condition: 'lightrain', translation: 'lätt regn', icon: '46.png' },
    { condition: 'lightsleet', translation: 'lätt blandat regn och snö', icon: '47.png' },
    { condition: 'heavysleet', translation: 'kraftigt blandat regn och snö', icon: '48.png' },
    { condition: 'lightsnow', translation: 'lätt snö', icon: '49.png' },
    { condition: 'heavysnow', translation: 'kraftigt snö', icon: '50.png' }
  ];
